name: Archive Pipeline

on:
  schedule:
    # First day of each month at 01:00 UTC
    - cron: "0 1 1 * *"
  workflow_dispatch:

jobs:
  run-archive:
    runs-on: ubuntu-latest
    env:
      NYT_API_KEY: ${{ secrets.NYT_API_KEY }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run pipeline
        run: |
          python pipelines/archived_articles_pipeline.py
